/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as CompoundRouteImport } from './routes/compound'
import { Route as DamRouteImport } from './routes/dam'
import { Route as HelplineRouteImport } from './routes/helpline'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as RainRouteImport } from './routes/rain'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as SectorGuidanceRouteImport } from './routes/sector-guidance'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundRoute = CompoundRouteImport.update({
  id: '/compound',
  path: '/compound',
  getParentRoute: () => rootRouteImport,
} as any)
const DamRoute = DamRouteImport.update({
  id: '/dam',
  path: '/dam',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplineRoute = HelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const RainRoute = RainRouteImport.update({
  id: '/rain',
  path: '/rain',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorGuidanceRoute = SectorGuidanceRouteImport.update({
  id: '/sector-guidance',
  path: '/sector-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/communities': typeof CommunitiesRoute
  '/compound': typeof CompoundRoute
  '/dam': typeof DamRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/phone': typeof PhoneRoute
  '/rain': typeof RainRoute
  '/readiness': typeof ReadinessRoute
  '/sector-guidance': typeof SectorGuidanceRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/communities': typeof CommunitiesRoute
  '/compound': typeof CompoundRoute
  '/dam': typeof DamRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/phone': typeof PhoneRoute
  '/rain': typeof RainRoute
  '/readiness': typeof ReadinessRoute
  '/sector-guidance': typeof SectorGuidanceRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/communities': typeof CommunitiesRoute
  '/compound': typeof CompoundRoute
  '/dam': typeof DamRoute
  '/helpline': typeof HelplineRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/phone': typeof PhoneRoute
  '/rain': typeof RainRoute
  '/readiness': typeof ReadinessRoute
  '/sector-guidance': typeof SectorGuidanceRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/communities'
    | '/compound'
    | '/dam'
    | '/helpline'
    | '/home'
    | '/login'
    | '/phone'
    | '/rain'
    | '/readiness'
    | '/sector-guidance'
    | '/signup'
    | '/simulator'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/communities'
    | '/compound'
    | '/dam'
    | '/helpline'
    | '/home'
    | '/login'
    | '/phone'
    | '/rain'
    | '/readiness'
    | '/sector-guidance'
    | '/signup'
    | '/simulator'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/communities'
    | '/compound'
    | '/dam'
    | '/helpline'
    | '/home'
    | '/login'
    | '/phone'
    | '/rain'
    | '/readiness'
    | '/sector-guidance'
    | '/signup'
    | '/simulator'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CommunitiesRoute: typeof CommunitiesRoute
  CompoundRoute: typeof CompoundRoute
  DamRoute: typeof DamRoute
  HelplineRoute: typeof HelplineRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PhoneRoute: typeof PhoneRoute
  RainRoute: typeof RainRoute
  ReadinessRoute: typeof ReadinessRoute
  SectorGuidanceRoute: typeof SectorGuidanceRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound': {
      id: '/compound'
      path: '/compound'
      fullPath: '/compound'
      preLoaderRoute: typeof CompoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dam': {
      id: '/dam'
      path: '/dam'
      fullPath: '/dam'
      preLoaderRoute: typeof DamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpline': {
      id: '/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof HelplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rain': {
      id: '/rain'
      path: '/rain'
      fullPath: '/rain'
      preLoaderRoute: typeof RainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector-guidance': {
      id: '/sector-guidance'
      path: '/sector-guidance'
      fullPath: '/sector-guidance'
      preLoaderRoute: typeof SectorGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CommunitiesRoute: CommunitiesRoute,
  CompoundRoute: CompoundRoute,
  DamRoute: DamRoute,
  HelplineRoute: HelplineRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PhoneRoute: PhoneRoute,
  RainRoute: RainRoute,
  ReadinessRoute: ReadinessRoute,
  SectorGuidanceRoute: SectorGuidanceRoute,
  SignupRoute: SignupRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
